### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by JemeryDay** [PacificCommunity/ofp-sam-yft-review#1]
The following link is broken:

https://github.com/PacificCommunity/ofp-sam-yft-review-analysis/blob/main/notes/stepwise-findings.md

Perhaps it should now point to this (but maybe you should check first?)

https://github.com/PacificCommunity/ofp-sam-yft-review-analysis/blob/main/notes/stepwise-changes.md

**Comment by arni-magnusson** [comment]
Good catch, fixed!
